### ISSUE TITLE
Washington DC TFR shows up for locations outside of the TFR

### ISSUE THREAD

**Issue by ooglek** [aeharding/ppg.report#107]
First off -- LOVE the TFR integration!!! I also love the weather, the METARs, and the Discussion and Report Metadata sections!!!

So the TFR for Washington DC really is not temporary, it's considered permanent. TFR FDC 1/1155

The problem is that many of the sites I fly are outside of the DC TFR 30nm ring (Called a SFRA, Special Flight Restriction Area), yet PPG.report continues to show the red warning sign.

KEZF, Shannon Airport, in Fredericksburg, VA, is both outside of the 30nm ring, as well as south of its southern-most border, yet ppg.report continues to show that TFR. I realize this is because the site is within 20 miles of my selected location, but truly, 80% of my flights are within 20 miles of the permanent flight restrictions.

I understand Washington DC is an exception here, maybe provide an option to ignore Permanent SFRAs? I still absolutely want to know about truly temporary TFRs, but the DC SFRA is not one of them! I took the FAA course, I have the certificate, I can fly in the 30-60nm SFRA Ring.

Thanks!

**Comment by aeharding** [comment]
Hey there! Thanks for the issue. This makes sense and I'll probably make a way to permanently hide any given TFR (resettable through settings).

**Comment by aeharding** [comment]
This should now be resolved with 3.7.0. Let me know if that solves your problem!

**Comment by ooglek** [comment]
@aeharding it does!!! Perfect, thanks! Definitely a weird edge case, I really appreciate you providing a means to hiding PFRs pretending to be TFRs! ;-) Cheers!

**Comment by ooglek** [comment]
Also, unrelated but since I'm here, the weather animations for rain are awesome!!! Super intuitive, very useful. Excellent improvement!
