### ISSUE TITLE
fontawesome-pro dependency blocks install

### ISSUE THREAD

**Issue by dopplerreflect** [aeharding/ppg.report#144]
`Error: https://harding.dev:23435/@fortawesome%2ffontawesome-pro/-/fontawesome-pro-5.15.4.tgz: Request failed "401 Unauthorized"`

I'd just like to contribute a few low-hanging UX tweeks, but would like to avoid having to pay for a fontawesome pro subscription to do so.

**Comment by whytf** [comment]
+1

**Comment by aeharding** [comment]
Should now work, try reinstalling. If you're having issues still lmk.

**Comment by whytf** [comment]
@aeharding 
> Should now work, try reinstalling. If you're having issues still lmk.

When building in cloudflare, it fails with this error:
```
error An unexpected error occurred: "https://harding.dev:23435/@fortawesome%2ffontawesome-svg-core/-/fontawesome-svg-core-1.2.36.tgz: Request failed \"404 Not Found\"".
```
